version: "3.7"
services:
  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: web
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    build: ./docker/postgres/
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    