version: "3.7"
services:
  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: web
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    build: ./docker/postgres/
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: cinema
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data
    secrets:
      - db_user
      - db_password
secrets:
  db_user:
    file: ./docker/secrets/db/secrets_user.txt
  db_password:
    file: ./docker/secrets/db/secrets_password.txt